server:
    port: 8888
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain
    servlet:
      context-path: /frontend-app
logging:
  config: classpath:log4j2.xml
  level:
    com: info
    com.maintian: debug